
name: 'dbtsnow'
version: '1.0.0'
config-version: 2

profile: 'dbtsnow'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "pruebas"  
clean-targets:         
  - "target"
  - "dbt_packages"

vars:
  source_schema_dev: GIMO_CASHFLOW
  source_schema_prod: GIMO_CASHFLOW_PROD

models:
  dbtsnow:
    example:
      +materialized: view
